### ISSUE TITLE
[BUG] thing doesn't start

### ISSUE THREAD

**Issue by Letrixix** [FuckingToasters/discord-group-spammer#12]
**Describe the bug**
Just, the thing doesn't start.

**To Reproduce**
Just follow the repl.it procedure.

**Expected behavior**
file to start

**Screenshots**
![image](https://user-images.githubusercontent.com/87038960/149823701-0e5adcb7-78fb-4bca-88fb-6a7e1a64ff26.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2

**Additional context**
please help me quick

**Comment by bryonpokemon** [comment]
this is patched

**Comment by Letrixix** [comment]
what does this mean?

**Comment by FuckingToasters** [comment]
You need to enter the command it is being executed to run the script. just enter `python all_together.py` However as already mentioned by @bryonpokemon the tool is patched (still works but not make much sense to use it for groupactions because of the ratelimit, that discord added a while ago) some options still work fine (member from guild fetcher as example)

Im working on something big :)

**Comment by FuckingToasters** [comment]
Closing this issue now as of inactivity.
