### ISSUE TITLE
[BUG] Program crash after selection any option

### ISSUE THREAD

**Issue by HellishFeline** [FuckingToasters/discord-group-spammer#15]
Every time I select an option it just crashes

**Comment by FuckingToasters** [comment]
Hello,
Im not sure on which OS you try to run it on but it seems like this happen on windows and probably macos but not on linux.
It probably raise an error and then directly close the program so you cant even see what the error was. You should try to open your Terminal manually, then cd in the dictonary where your all_together.py is located at using following command: `cd path`
After that run the program inside the terminal, make sure to include the keyword `python` so you should execute the file using `python all_together.py` instead of just `all_together.py` this should show you the error without closing the window so you can copy the error and send it here and then i can take a look at it.

Rember tho, discord added a 30 seconds ratelimit and included the time to sleep in their api endpoint so i updated the program to sleep as long as you got ratelimited. Some API endpoint ratelimits are bound to the IP and proxies would help to bypass it e.g creating a discord account. Some api endpoints bind the ratelimit to the account so i already thought about adding multiaccount support however this make no sense as i dont think that your victim will accept a lot of friendrequests :)
