### ISSUE TITLE
add multi token support

### ISSUE THREAD

**Issue by cepersk** [FuckingToasters/discord-group-spammer#21]
this would make up for quite a bit of the time limit imposed by the discord api

**Comment by FuckingToasters** [comment]
When i initially created this project everything went fine without proxies & multi token support. Now that discord added the ratelimit i already thought about adding multi token support but i'm not quite sure how i should implement it because your victim probably don't want to accept 1K Friend requests from different accounts :)

**Comment by cepersk** [comment]
Having used the program, I managed to make 1000 groups in total while one victim was sleeping. I think you can add the victim with about 4 different accounts. That makes a big difference.

**Comment by FuckingToasters** [comment]
> Having used the program, I managed to make 1000 groups in total while one victim was sleeping. I think you can add the victim with about 4 different accounts. That makes a big difference.
> 

Hmm yea that's true but to add someone you'll need to have them in the friendlist. So if you want to use 4 different accounts you'll need to make that the victim accept every friend request. With just 4 accounts this might be a great option but if you consider using 1K tokens and don't want to send the requests manually I'm sure that the victim don't accept the 1K incoming requests.

However, I'm going to implement this.
